version: '3'

services:
  consultorioDB:
    image: postgres:16
    container_name: consultorio-db
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=manager
      - POSTGRES_DB=consultorio
    volumes:
      - ./postgres:/var/lib/postgresql/data